### ISSUE TITLE
Socket fail error onstart 

### ISSUE THREAD

**Issue by madibalive** [ParsePlatform/ParseLiveQuery-Android#15] opened 2017-03-20 12:28 UTC
Hi am currently trying to use this library ,but i cant pass this error
code for am using ,would appreciate any help thanks .

```
 ParseLiveQueryClient<ParseObject> parseLiveQueryClient = null;
            try {
                parseLiveQueryClient = ParseLiveQueryClient.Factory.getClient(new URI("wss://alphatest.back4app.io"));

                ParseQuery<ParseObject> query= ParseQuery.getQuery("Message");
                query.whereEqualTo("to",toObject);
                SubscriptionHandling<ParseObject> subscriptionHandling = parseLiveQueryClient.subscribe(query);

                subscriptionHandling.handleEvent(SubscriptionHandling.Event.CREATE, (query1, object) -> {
                    // HANDLING create event

                });

            } catch (URISyntaxException e1) {
                Log.e("CHAT", "onFinish: error "+e.getMessage() );
                e1.printStackTrace();
            }
```
ERROR PRODUCE 
```
: Socket onError
com.firebase.tubesock.WebSocketException: connection failed: unknown status code 400
at com.firebase.tubesock.WebSocketHandshake.verifyServerStatusLine(WebSocketHandshake.java:91)
at com.firebase.tubesock.WebSocket.runReader(WebSocket.java:357)
at com.firebase.tubesock.WebSocket.access$000(WebSocket.java:30)
at com.firebase.tubesock.WebSocket$2.run(WebSocket.java:108)
at java.lang.Thread.run(Thread.java:818)
```

**Comment by mmimeault** [comment] 2017-03-22 14:14
Maybe the problem is related to the fact you try to use `wss` (secured ws). 
@flovilmart Do you know if wss is properly supported by the parse server?

**Comment by flovilmart** [comment] 2017-03-22 14:16
It depends how you start it, the CLI don't provide an interface for the wss, if you have HaProxy or Nginx properly configured for HTTPS, that should work

**Comment by rogerhu** [comment] 2017-03-27 18:56
Going to close this ticket.  1.0.1 release will no longer require a uri and infer it from the parse unit config.  That said if you are running on Elastic beanstalk or don't have websockets configured properly you will get similar issues

**Closed** 2017-03-27 18:56 UTC
